name: GitHub Actions Demo
on: workflow_dispatch
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Print to console
        run: echo Hello Git Actions
      - name: Print Make
        run : |
          echo First line!
          echo Second line!