name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing say-hello
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: make say-hello 'Hello, World'